stages:
  - build
  - test_backend
  - test_frontend


build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t react_django_backend:latest backend
    - docker build -t react_django_frontend:latest frontend
test_backend:
  stage: test_backend
  image: react_django_backend:latest
  script:
    - python manage.py test
test_frontend:
  stage: test_frontend
  image: react_django_frontend:latest
  script:
    - npm run test
