stages:
  - build_backend
  - test_backend
  - build_frontend
  - test_frontend
variables:
  IMAGE: ${DOCKER_USER}/${DOCKER_REGISTRY}

build_backend:
  stage: build_backend
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo $DOCKER_AUTH_CONFIG
    - docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - docker pull shimengchen/backend:latest || true
    - docker build --cache-from shimengchen/backend:latest -t shimengchen/backend:latest backend
    - docker run shimengchen/backend:latest python3 manage.py test --settings=hello_world.settings.development
    - docker push shimengchen/backend:latest
    
test_backend:
  stage: test_backend
  image: shimengchen/backend:latest
  script:
    - python3 ./backend/manage.py test --settings=hello_world.settings.development

build_frontend:
  stage: build_frontend
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo $DOCKER_AUTH_CONFIG
    - docker login -u $DOCKER_USER -p $DOCKER_PASS 
    - docker pull shimengchen/frontend:latest || true
    - docker build --cache-from shimengchen/frontend:latest -t shimengchen/frontend:latest frontend
    - docker push shimengchen/frontend:latest
test_frontend:
  stage: test_frontend
  image: shimengchen/frontend:latest
  script:
    - npm run test
