version: '3'

services:
  backend:
    image: shimengchen/backend
    #command: bash -c ""
    command: ["sh", "entry.sh"]
    volumes:
    - web_app:/code

  nginx:
    image: shimengchen/nginx
    ports:
      - "80:8000"
    volumes:
    - web_app:/code
    #volumes_from:
    # - backend
volumes:
  web_app:
    driver: local
    driver_opts:
      type: none
      device: /home/chenshm/miniproject/virtual-env-blueprint/bin/backend
      o: bind